# 0. Chuẩn bị môi trường
Kiểm tra và cài đặt các thư viện cần thiết. Các thư viện đã được cấu hình sẵn trong `requirements.txt`.
Đảm bảo đã cài đặt `duckdb`, `pandasql`, `pyarrow` để hỗ trợ truy vấn SQL và parquet.

In [ ]:
!pip install -r requirements.txt

# 1. Import dataset CSV, JSON và chuyển đổi Parquet
Chuyển đổi dữ liệu sang định dạng Parquet để tăng tốc độ I/O và tối ưu bộ nhớ.
Đồng thời load dữ liệu JSON chứa nhãn đánh giá thủ công `TripAdvisor_EN.json` để chuẩn bị xây dựng Chatbot.

In [ ]:
import os
import json
import pandas as pd
import duckdb
import matplotlib.pyplot as plt
import seaborn as sns

DATA_DIR = 'data/dataset'
os.makedirs(DATA_DIR, exist_ok=True)
raw_csv_path = os.path.join(DATA_DIR, 'tripadvisor_review_hotel_dataset.csv')
clean_pq_path = os.path.join(DATA_DIR, 'tripadvisor_reviews_clean.parquet')
json_path = os.path.join(DATA_DIR, 'TripAdvisor_EN.json')

# Load JSON
parsed_rationales = []
if os.path.exists(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        raw_annotations = json.load(f)
    print(f"Loaded {len(raw_annotations)} reviews from JSON.")
else:
    print(f"Không tìm thấy file {json_path}")

# Load Parquet hoặc chuyển CSV sang Parquet
if os.path.exists(clean_pq_path):
    df_reviews = pd.read_parquet(clean_pq_path)
    print(f"Loaded Parquet file with {len(df_reviews)} records.")
elif os.path.exists(raw_csv_path):
    print("Converting CSV to Parquet...")
    df_reviews = pd.read_csv(raw_csv_path)
    df_reviews.to_parquet(clean_pq_path, engine='pyarrow', index=False)
    print(f"Saved Parquet file at {clean_pq_path}")
else:
    print(f"Không tìm thấy cả {clean_pq_path} và {raw_csv_path}")
    df_reviews = pd.DataFrame()

# 2. SQL Queries cho các Research Questions (RQs)
- **RQ1**: Ảnh hưởng của việc chuyển từ 2 lớp sang 5 mức đối với điểm số Rationalization.
- **RQ2**: Đo lường Cross-Aspect Leakage (Sự rò rỉ giữa các khía cạnh).
- **RQ3**: Hiệu quả của hàm mất mát CORN (Ordinal Loss) và Phạt chồng lấn.

In [ ]:
# Truy vấn mô phỏng RQ1 và RQ2 qua DuckDB trên Parquet
try:
    con = duckdb.connect(database=':memory:')
    
    print("--- Phân tích RQ1: Thống kê điểm số đa khía cạnh theo thang 5 mức ---")
    query_rq1 = """
    SELECT 
        normalized_score AS Overall_Rating,
        COUNT(*) as Review_Count,
        AVG(CAST(Location AS FLOAT)) as Avg_Location,
        AVG(CAST(Service AS FLOAT)) as Avg_Service,
        AVG(CAST(Cleanliness AS FLOAT)) as Avg_Cleanliness
    FROM read_parquet('data/dataset/tripadvisor_reviews_clean.parquet')
    GROUP BY normalized_score
    ORDER BY normalized_score
    """
    rq1_stats = con.execute(query_rq1).df()
    display(rq1_stats)
    
    print("\n--- Phân tích RQ2: Kiểm tra độ tương quan chéo (Leakage) cơ bản ---")
    query_rq2 = """
    SELECT 
        CORR(CAST(Service AS FLOAT), CAST(Cleanliness AS FLOAT)) as Corr_Service_Cleanliness,
        CORR(CAST(Location AS FLOAT), CAST(Service AS FLOAT)) as Corr_Location_Service
    FROM read_parquet('data/dataset/tripadvisor_reviews_clean.parquet')
    """
    rq2_corr = con.execute(query_rq2).df()
    display(rq2_corr)
    
except Exception as e:
    print("DuckDB query error (có thể file parquet chưa sẵn sàng):", e)

# 3. EDA và Data Cleaning
Làm sạch dữ liệu, xử lý missing values. Đối với các khía cạnh bị thiếu, chúng ta sẽ gán bằng điểm tổng quan (`normalized_score`).

In [ ]:
if not df_reviews.empty:
    print("Missing values in dataset (before):")
    print(df_reviews[['normalized_score', 'Location', 'Service', 'Cleanliness']].isnull().sum())
    
    # Fill missing values
    aspects = ['Location', 'Service', 'Cleanliness', 'Value', 'Rooms']
    for col in aspects:
        if col in df_reviews.columns:
            # Ép kiểu số
            df_reviews[col] = pd.to_numeric(df_reviews[col], errors='coerce')
            # Điền thiếu bằng normalized_score
            df_reviews[col] = df_reviews[col].fillna(df_reviews['normalized_score'])
            # Clip trong khoảng 1-5
            df_reviews[col] = df_reviews[col].fillna(3).astype(int).clip(1, 5)
            
    df_reviews['normalized_score'] = pd.to_numeric(df_reviews['normalized_score'], errors='coerce').fillna(3).astype(int).clip(1, 5)
    
    print("\nMissing values (after cleaning):")
    print(df_reviews[['normalized_score', 'Location', 'Service', 'Cleanliness']].isnull().sum())

# 4. Visualization
Trực quan hóa phân bố điểm số để củng cố giả thuyết cho RQ1 (Dữ liệu bị lệch về mức đánh giá cao 4-5 sao).
Và trực quan hóa ma trận tương quan cho RQ2.

In [ ]:
if not df_reviews.empty:
    aspects_to_plot = ['Location', 'Service', 'Cleanliness']
    valid_aspects = [a for a in aspects_to_plot if a in df_reviews.columns]
    
    if valid_aspects:
        # 5-level Rating Distribution
        fig, axes = plt.subplots(1, len(valid_aspects), figsize=(16, 4))
        for i, aspect in enumerate(valid_aspects):
            ax = axes[i] if len(valid_aspects) > 1 else axes
            sns.countplot(x=df_reviews[aspect], ax=ax, palette='Blues_r')
            ax.set_title(f"{aspect} Rating Distribution (1-5)")
            ax.set_xlabel("Star Rating")
            ax.set_ylabel("Count")
        plt.suptitle("5-Level Ordinal Class Imbalance (RQ1)", y=1.05)
        plt.tight_layout()
        plt.show()
        
        # Correlation Matrix
        corr = df_reviews[valid_aspects].corr()
        plt.figure(figsize=(6, 5))
        sns.heatmap(corr, annot=True, cmap='coolwarm', vmin=0.4, vmax=1.0)
        plt.title("Correlation Matrix Between Aspects (RQ2)")
        plt.show()

# 5. Feature Engineering

**Feature**

In [ ]:
# Tạo DataFrame chứa review và rationale

feature_df = pd.DataFrame({
    "review_id": range(len(parsed_rationales)),
    "text": [x["text"] for x in parsed_rationales],
    "rationales": [x["rationales"] for x in parsed_rationales]
})

ASPECTS = [
    "Service",
    "Facility",
    "Amenity",
    "Experience",
    "Loyalty",
    "Branding"
]

print("Feature dataframe:", feature_df.shape)

feature_df.head()

Feature dataframe: (9990, 3)

,review_id,text,rationales
0,0,"We enjoyed our stay here, the hotel is as you ...","{'Service': [{'start': 213, 'end': 297, 'text'..."
1,1,I would thank hotel team and specially managem...,"{'Experience': [{'start': 0, 'end': 68, 'text'..."
2,2,Quoc was the perfect host. Catered for literal...,"{'Loyalty': [{'start': 260, 'end': 286, 'text'..."
3,3,In the pool as I type this. Hotel is wonderful...,"{'Service': [{'start': 48, 'end': 71, 'text': ..."
4,4,"Beautiful hotel, very friendly staff. Right on...","{'Facility': [{'start': 0, 'end': 14, 'text': ..."

In [ ]:
# Feature 1: Aspect Coverage

def calculate_aspect_coverage(rationales):
    detected_aspects = [
        aspect
        for aspect in ASPECTS
        if len(rationales.get(aspect, [])) > 0
    ]

    coverage = len(detected_aspects) / len(ASPECTS)

    return coverage


feature_df["aspect_coverage"] = feature_df["rationales"].apply(
    calculate_aspect_coverage
)

print("Thống kê Aspect Coverage:")
print(feature_df["aspect_coverage"].describe())

print("\nMột số review mẫu:")
display(
    feature_df[
        ["review_id", "text", "aspect_coverage"]
    ].head(10)
)

Thống kê Aspect Coverage:
count    9990.000000
mean        0.557908
std         0.177149
min         0.000000
25%         0.500000
50%         0.500000
75%         0.666667
max         1.000000
Name: aspect_coverage, dtype: float64

Một số review mẫu:

,review_id,text,aspect_coverage
0,0,"We enjoyed our stay here, the hotel is as you ...",0.500000
1,1,I would thank hotel team and specially managem...,0.500000
2,2,Quoc was the perfect host. Catered for literal...,0.666667
3,3,In the pool as I type this. Hotel is wonderful...,0.500000
4,4,"Beautiful hotel, very friendly staff. Right on...",0.333333
5,5,Beautiful buildings and facilities. Our room w...,0.333333
6,6,A modern and friendly Hotel to stay at in Hano...,0.333333
7,7,Really nice place to stay in Hoi An. Very clea...,0.500000
8,8,The hotel is absolutely amazing. It have incre...,0.500000
9,9,Service excellence began even before we stayed...,0.666667

In [ ]:
# Feature 2: Aspect Dominance
# Aspect chiếm tỷ trọng evidence lớn nhất trong review
# Cho biết aspect nào là chủ đề chính của review dựa trên số rationale.

def get_aspect_dominance(rationales):
    rationales = rationales or {}
    counts = {
        aspect: len(rationales.get(aspect, []))
        for aspect in ASPECTS
    }

    total = sum(counts.values())
    if total == 0:
        return None, 0.0

    dominant_aspect, dominant_count = max(
        counts.items(),
        key=lambda item: (item[1], -ASPECTS.index(item[0]))
    )

    return dominant_aspect, dominant_count / total

dominance_df = pd.DataFrame(
    feature_df["rationales"].apply(get_aspect_dominance).tolist(),
    columns=["dominant_aspect", "aspect_dominance"],
    index=feature_df.index
)

feature_df = pd.concat([feature_df, dominance_df], axis=1)

feature_df[["text", "dominant_aspect", "aspect_dominance"]].head()

,text,dominant_aspect,aspect_dominance
0,"We enjoyed our stay here, the hotel is as you ...",Service,0.400000
1,I would thank hotel team and specially managem...,Experience,0.428571
2,Quoc was the perfect host. Catered for literal...,Service,0.285714
3,In the pool as I type this. Hotel is wonderful...,Service,0.500000
4,"Beautiful hotel, very friendly staff. Right on...",Facility,0.600000

In [ ]:
# Feature 4: Sentiment Polarity Strength
# Tỷ lệ rationale có cảm xúc rõ (Positive hoặc Negative).

def polarity_strength(rationales):
    sentiments = [
        span.get("sentiment", "Neutral")
        for spans in rationales.values()
        for span in spans
    ]

    if not sentiments:
        return 0.0

    clear_sentiments = sum(
        sentiment in ["Positive", "Negative"]
        for sentiment in sentiments
    )
    return clear_sentiments / len(sentiments)


feature_df["polarity_strength"] = (
    feature_df["rationales"]
    .apply(polarity_strength)
)

feature_df[["text", "polarity_strength"]].head()

In [ ]:
# Feature 5: Sentiment Conflict
# Tỷ lệ aspect được đề cập có cả rationale Positive lẫn Negative.

def sentiment_conflict_ratio(rationales):
    conflict_count = 0
    mentioned_aspect_count = 0
    valid_sentiments = {"Positive", "Neutral", "Negative"}

    for aspect in ASPECTS:
        sentiments = [
            span.get("sentiment", "Neutral")
            for span in rationales.get(aspect, [])
            if span.get("sentiment", "Neutral") in valid_sentiments
        ]

        if sentiments:
            mentioned_aspect_count += 1

        if "Positive" in sentiments and "Negative" in sentiments:
            conflict_count += 1

    if mentioned_aspect_count == 0:
        return 0.0

    return conflict_count / mentioned_aspect_count


feature_df["sentiment_conflict_ratio"] = (
    feature_df["rationales"]
    .apply(sentiment_conflict_ratio)
)

feature_df[["text", "sentiment_conflict_ratio"]].head()

In [ ]:
# Feature 6: Aspect Sentiment Consistency
# Trung bình mức đồng thuận sentiment giữa nhiều rationale cùng aspect.

def sentiment_consistency(rationales):
    consistency_scores = []
    valid_sentiments = {"Positive", "Neutral", "Negative"}

    for aspect in ASPECTS:
        sentiments = [
            span.get("sentiment", "Neutral")
            for span in rationales.get(aspect, [])
            if span.get("sentiment", "Neutral") in valid_sentiments
        ]

        if len(sentiments) < 2:
            continue

        consistency_scores.append(
            max(sentiments.count(sentiment) for sentiment in valid_sentiments)
            / len(sentiments)
        )

    if not consistency_scores:
        return np.nan

    return np.mean(consistency_scores)


feature_df["sentiment_consistency"] = (
    feature_df["rationales"]
    .apply(sentiment_consistency)
)

feature_df[["text", "sentiment_consistency"]].head()

In [ ]:
# Feature 7: Evidence Density
# Mật độ evidence trên mỗi từ của review

def evidence_density(row):
    text = row["text"]
    word_count = len(re.findall(r"\b\w+\b", text))

    evidence_count = sum(
        len(row["rationales"].get(aspect, []))
        for aspect in ASPECTS
    )

    if word_count == 0:
        return 0.0

    return evidence_count / word_count


feature_df["evidence_density"] = feature_df.apply(
    evidence_density,
    axis=1
)

feature_df[["text", "evidence_density"]].head()

In [ ]:
# Feature 8: Evidence Length Score
# Độ dài evidence trung bình đã chuẩn hóa theo mốc 10 từ.

def evidence_length_score(rationales):
    word_counts = [
        len(re.findall(r"\b\w+\b", span.get("text", "").strip()))
        for spans in rationales.values()
        for span in spans
        if span.get("text", "").strip()
    ]

    if not word_counts:
        return 0.0

    return min(np.mean(word_counts) / 10.0, 1.0)


feature_df["evidence_length_score"] = (
    feature_df["rationales"]
    .apply(evidence_length_score)
)

feature_df[["text", "evidence_length_score"]].head()

In [ ]:
# Feature 9: Cross-Aspect Overlap
# Tỷ lệ evidence xuất hiện ở nhiều aspect.

def cross_aspect_overlap(rationales):
    span_map = {}

    for aspect in ASPECTS:
        for span in rationales.get(aspect, []):
            key = (
                span.get("start"),
                span.get("end"),
                span.get("text", "").strip()
            )
            span_map.setdefault(key, set()).add(aspect)

    if not span_map:
        return 0.0

    overlapping = sum(
        len(aspects_used) > 1
        for aspects_used in span_map.values()
    )
    return overlapping / len(span_map)


feature_df["cross_aspect_overlap"] = (
    feature_df["rationales"]
    .apply(cross_aspect_overlap)
)

feature_df[["text", "cross_aspect_overlap"]].head()

In [ ]:
# Feature 10: QA Relevance Score
# Điểm phù hợp của review đối với Evidence-Grounded QA

feature_df["qa_relevance_score"] = (
    0.20 * feature_df["aspect_coverage"]
    + 0.20 * feature_df["aspect_dominance"]
    + 0.15 * feature_df["evidence_density"]
    + 0.20 * feature_df["evidence_length_score"]
    + 0.15 * feature_df["sentiment_consistency"]
    + 0.10 * (1 - feature_df["cross_aspect_overlap"])
)

feature_df[
    [
        "aspect_coverage",
        "aspect_dominance",
        "evidence_density",
        "evidence_length_score",
        "sentiment_consistency",
        "cross_aspect_overlap",
        "qa_relevance_score"
    ]
].head()

# 6. Chuẩn bị chạy `Training_Kaggle.ipynb` trên Kaggle
Các bước cần thiết còn lại để chuyển đổi pipeline này sang môi trường huấn luyện Kaggle:
1. **Upload Dataset:** Nén thư mục `data/dataset` (đặc biệt là file `tripadvisor_reviews_features.parquet` và `TripAdvisor_EN.json`) và upload lên Kaggle.
2. **Cập nhật Path:** Mở `Training_Kaggle.ipynb` trên Kaggle, điều chỉnh biến `DATA_DIR` thành `/kaggle/input/tên-dataset-của-bạn`.
3. **Cài đặt thư viện GPU:** Nếu mô hình là PLMR (như báo cáo trong RQ3), chạy `!pip install transformers datasets accelerate duckdb pyarrow` ở cell đầu tiên.
4. **Kiến trúc Loss (RQ3):** Kiểm tra lại phần code mô phỏng hàm loss CORN và phạt chồng lấn giữa các khía cạnh trong `Training_Kaggle.ipynb`.
5. **Chọn Accelerator:** Bật GPU T4 x2 hoặc P100 trên kernel Kaggle.

In [ ]:
print("Hoàn tất tái cấu trúc! Hệ thống sẵn sàng cho bước Training trên Kaggle.")